### ISSUE TITLE
Make the search field the default when creating a new book note

### ISSUE THREAD

**Issue by PowerSchill** [anpigon/obsidian-book-search-plugin#105]
When you create a new book note, the search dialog defaults to the language instead of the search field. You can start typing your search by setting the default to the search field. Currently, I am changing the language because I am typing without changing fields.

**Comment by Rdkang** [comment]
I had the same problem and glad to find a new setting called "Ask for Locale" which if disabled hides the locale field :)

**Comment by PowerSchill** [comment]
I should have looked closer at the options but thanks for pointing it out.
