### ISSUE TITLE
Google API Not Saving or Staying Enabled

### ISSUE THREAD

**Issue by aaronjz** [anpigon/obsidian-book-search-plugin#107]
When I toggle the Google API Settings, then paste the API key and click save, it tells me it saves the API key. However, when I close out of the plugin settings and open it back up, the Google API settings is toggled off. When I toggle it back on, sometimes the API key is still there, but more often than not it is blank again. 

Really appreciate this plugin. I would love to see this minor issue figured out. Thanks.

**Comment by luckylat** [comment]
Thanks! I'm a contributer about the feature.

> Google API settings will toggle off after close
The toggle is just means open/close the setting, but I agree that behavior looks like strange. I will make a PR to stop using createFoldingHeader.

> API key will blank
This is correct behavior for security reason(You can imagine about GitHub SSH Key Setting) and API key is surely saved.
but, from a UX perspective, the behavior occur surely confusing. 
I want to fix this by adding a ping function.
