### ISSUE TITLE
Custom text to frontmatter without underscores

### ISSUE THREAD

**Issue by ainselx** [anpigon/obsidian-book-search-plugin#11]
Currently text is added **with** underscores. Can the underscore be removed please?
![image](https://user-images.githubusercontent.com/5066815/166940610-4c053d6c-2265-4c87-a8d8-5ac4059b8b1c.png)

**Comment by anpigon** [comment]
I will add the option to choose "Snake Case" or "Camel Case".

**Comment by ainselx** [comment]
thanks, pal.
if you ever include you pay pal  or other version of donation button to the plugin description - coffee is on me!)
