### ISSUE TITLE
Impossible to insert book contains special symbols in name

### ISSUE THREAD

**Issue by infectormp** [anpigon/obsidian-book-search-plugin#27]
If book name contains special symbols will be impossible insert it to Obsidian
![image](https://user-images.githubusercontent.com/9958813/175224635-5d2e6fcc-7fbe-4271-bc2d-ef68ab300276.png)
![image](https://user-images.githubusercontent.com/9958813/175224848-bf9ec675-b788-492b-abc3-97b748373cd6.png)

**Comment by stefwill** [comment]
Would it be possible to set an auto replace all special characters with a user selected character?

**Comment by anpigon** [comment]
fixed

**Comment by Superelmanu** [comment]
The issue continues to occur in v 0.55 
If you are truing to add, Who was J.R.R Tolkien? You do have the same message, “File can contain any of the …”
Look for who was Tolkien, it's the first book in the list.

**Comment by stefwill** [comment]
Can confirm the issue is still occurring in Version 0.5.5
