### ISSUE TITLE
[Feature Request] Include Subtitle in data pulled from Google Books API

### ISSUE THREAD

**Issue by vJourneyman** [anpigon/obsidian-book-search-plugin#36]
There's times where books have a common, single-word title with a more descriptive subtitle. It would be helpful in the note I'm creating to have that subtitle to add context and disambiguate similar works. And/Or maybe the publisher description? 

Example:
ISBN10:  0735214492
title: Range
subtitle: Why Generalists Triumph in a Specialized World

**Comment by anpigon** [comment]
Good Idea 👍🏻

**Comment by sruckel** [comment]
I searched for Renewal Theology and Google's title included the subtitle which made the YAML invalid.The following was the title from Google-- Renewal Theology: The Church, the kingdom, and last things. When I removed the subtitle and had just Renewal Theology remaining, it worked
Any Suggestions?

**Comment by anpigon** [comment]
@vJourneyman  ＠joss-enet helped me. We added a subtitle to version 0.5.7.

@sruckel You can use double quotes. (example: `Title: "Renewal Theology: The Church, the kingdom, and last things."`)
