### ISSUE TITLE
Booksearch - Frontmatter and content setting keeps being close  after being selected

### ISSUE THREAD

**Issue by robert-canuel** [anpigon/obsidian-book-search-plugin#37]
Hi,
Frontmatter and content setting keeps being close  after being selected..... So i cannot use the command [Create  Book Note] as it does not popup for us to enter a book name... In version 4.1 everything works fine

By the way thanks a lot for having created this very useful plugin...
Robert

**Comment by ceccadroid** [comment]
Same as per Issue #35

**Comment by anpigon** [comment]
This issue is fixed in version 0.5.5.
@robert-canuel @ceccadroid thank you.
