### ISSUE TITLE
Status 429

### ISSUE THREAD

**Issue by Ayazy21** [anpigon/obsidian-book-search-plugin#47]
Every time I try to add a new Book note, it gives me an "Error: Request failed, status 429."

**Comment by anpigon** [comment]
It is using Google book API. However, if you make too many requests, a status 429 error occurs. I'll try to figure out a solution.

**Comment by Ayazy21** [comment]
It somehow works now. I think there was a problem with the API.

**Comment by Knurris** [comment]
the google books API do not show in the restriction list. what should i choose?

**Comment by Knurris** [comment]
> the google books API do not show in the restriction list. what should i choose?

I had to go to the api and serveces library to eneble google books api
