### ISSUE TITLE
Cannot create title with question mark in it

### ISSUE THREAD

**Issue by fishcasa** [anpigon/obsidian-book-search-plugin#50]
When I find a book in search and try to add it, if it has a "?" in the title, the note fails to create and I get the following error
Error: file name cannot contain any of the following characters:

It would be great if there was an opportunity to edit the proposed title and continue with creation.

![image](https://user-images.githubusercontent.com/4305537/194721525-de1910eb-bd59-4abe-8d2b-99eb86659f70.png)

![image](https://user-images.githubusercontent.com/4305537/194721538-c947a6f6-e91d-4ce6-a591-32ce47596c0a.png)

![image](https://user-images.githubusercontent.com/4305537/194721621-06ae4166-adb3-46b6-a6db-cd18529786fa.png)

Windows 11
Obsidian 0.16.5
Book Search Plugin 0.5.8

**Comment by JordanChoe** [comment]
Having the same issue, however I have noticed that titles with ampersands are having them deleted automatically and the file is created.  Would it be possible to simply have the file creation delete the question mark?  I'm not sure if colons in a title (title:subtitle) are auto adjusted.

**Comment by JordanChoe** [comment]
Colons do autodelete for file names.
![Screenshot (337)](https://user-images.githubusercontent.com/108248499/195440219-60a3eefb-4642-4efd-8ee5-a317bf2ef3fd.png)

**Comment by wyldphyre** [comment]
I was just starting to check this plugin out and I hit this problem on the first book I looked for. It's definitely a show stopper for being able to use this to build a book catalog.

**Comment by ramarivera** [comment]
+1, it would be nice if there was a way to clean the illegal characters from the book title.

For example, Movies script and Videogame script do something like this to clean it up:

```
function replaceIllegalFileNameCharactersInString(string) {
  return string.replace(/[\\,#%&\{\}\/*<>?$\'\":@]*/g, "");
}
```
