### ISSUE TITLE
Getting an error when creating new book note

### ISSUE THREAD

**Issue by CryptoPensioner** [anpigon/obsidian-book-search-plugin#64]
When I try to create a new book note, I get an error:
'Error: ENOENT: no such file or directory,' and a file path to a note that it suppose to create. 

When I create the note myself and use the "Insert the metadata" option, it works fine.
It worked before and stopped for no reason. I have tried with all other plugins disabled - same error. Any idea what could be causing this?

I'm on Win10. Obsidian and all the plugins are up to date. No system changes.

**Comment by joestarrd** [comment]
Does the directory exist? 

Check settings to see what directory new files are set to. If you created the directory, make sure the folder exists

**Comment by CryptoPensioner** [comment]
Yes, the directory that was set was in there. 
I have no idea what was the issue but the latest update fixed it and it creates notes again.
