### ISSUE TITLE
[Feature Request] Multiple prefered locale languages. 

### ISSUE THREAD

**Issue by BusterBlade5** [anpigon/obsidian-book-search-plugin#68]
I'd love it if the plugin had the option to search for books in multiple languages. As a bilingual reader who frequently switches between reading in Spanish and English, it can be cumbersome to constantly change the language settings when searching for books

**Comment by BusterBlade5** [comment]
@anpigon

**Comment by Weltenkreuzer** [comment]
I did actually find a workaround for this: In the .obsidian/plugins - Folder in your vault you can create a copy of the folder "obsidian-book-search-plugin" and rename it to e.g. "obsidian-book-search-plugin-deutsch". Then you can open the manifest.json file and change id and data:

```
"id": "obsidian-book-search-plugin-deutsch",
"name": "Book Search Deutsch",
```

If you restart Obsidian now you get a second installation of the plugin where you can set a different locale. You can now use one command to search for one language and another for another...

**Comment by TheOneLight** [comment]
I also would like to search through multiple language areas. Many non-native English speakers are multilingual, or at least know enough languages to read, besides English, also in their mother tongue as well as one or two or even more other languages (and also have books in their libraries in two, three, or perhaps even more languages), so always having to go to the settings and switch between languages is not really the most practical solutions. It would be good to either be able to search through all language areas, or at least choose from the search panel one, two or even three (the more the better) languages to search across at the same time. Or at least be able to switch between languages directly from the search field.

**Comment by ruben-sg** [comment]
+1! Would love to have that possibility

**Comment by loerzi** [comment]
+1 Support this feature request, too. Thanks to @Weltenkreuzer for the workaround!

**Comment by ruben-sg** [comment]
Love it, Thanks so much!

**Comment by loerzi** [comment]
So do I. Thanks a lot 👍
