### ISSUE TITLE
Add option for dataview inline metadata in addition to YAML

### ISSUE THREAD

**Issue by rushikb** [anpigon/obsidian-book-search-plugin#7]
I love this plugin so much! One suggestion I would have that would be super helpful would be the ability to support dataview inline fields in the form of Key:: value. It makes things a lot easier to click through

**Comment by anpigon** [comment]
@rushikb 
Thanks for the good ideas. I'll try it today.

**Comment by anpigon** [comment]
Templates are supported in version 5.2.0. So you can use dataview inline fields.
