### ISSUE TITLE
[BUG] Book Search info not auto-filling after Properties update

### ISSUE THREAD

**Issue by TinkerSquirrel** [anpigon/obsidian-book-search-plugin#81]
I have several Properties set up for my book notes that are supposed to autofill using the plugin's data. Since the most recent Properties update, that's not happening. This is what the frontmatter looks like in source mode:

```
cover: "{coverUrl}"
title: "{title}"
author: "{author}"
category: "{category}"
```
And this is what's outputted in the Properties field when I create a new book note:

<img width="311" alt="image" src="https://github.com/anpigon/obsidian-book-search-plugin/assets/87002593/dd678f36-cf0c-438a-81c7-33622c8b0679">

Have I messed up the formatting, or is this a plugin issue?

**Comment by luckylat** [comment]
It may be 
```
cover: "{{coverUrl}}"
title: "{{title}}"
author: "{{author}}"
category: "{{category}}"
```

**Comment by TinkerSquirrel** [comment]
Ah, it was the double brackets that did the trick. Weird that they didn't carry over from the old YAML when Properties was introduced. Thanks!

**Comment by jun6lee** [comment]
I'm having trouble adding new books:

![CleanShot 2023-10-01 at 11 47 31](https://github.com/anpigon/obsidian-book-search-plugin/assets/6542146/c3801152-9527-4b99-89b5-cc76fb784c0a)

I've tried authors as both `{authors}` as well as `{{authors}}` and with speech marks around it.

**Comment by TinkerSquirrel** [comment]
All the template variables are singular, not plural. If you change it to {{author}} it should work.

All the variables are listed here if you need to double check any others: https://github.com/anpigon/obsidian-book-search-plugin#template-variables-definitions
