### ISSUE TITLE
[Feature Request] Subtitle

### ISSUE THREAD

**Issue by Xtremefaith** [anpigon/obsidian-book-search-plugin#84]
Not sure how difficult this would be, but it would be great if we could also get a `{{subtitle}}` variable to include in the template, I typically capture both when doing this manually so would be awesome of this plugin made it possible to automate that as well.

**Comment by yohanan** [comment]
@Xtremefaith as far as i can tell, `{{subtitle}}` is already available as a variable -- though it is not (yet) listed in the documentation.

i see it in the code, and here is the [commit](https://github.com/anpigon/obsidian-book-search-plugin/commit/f5df652387d2e6e55f15e13c7b98cdb7605c95c3#diff-c5a6258595047ee10b44073f1656a3879953633ff36a447d46478c870254f8cf).

there is also a [discussion](https://github.com/anpigon/obsidian-book-search-plugin/discussions/82#discussioncomment-7183828) that references the variable as well.

i would assume it is only populated if the Google Books API returns it as a separate property.

**Comment by MurtadhaInit** [comment]
Just came across this now and I agree with @yohanan the variable seems to exist but it's not being documented.
