### ISSUE TITLE
[SOLVED] Book's plot

### ISSUE THREAD

**Issue by ilcecca** [anpigon/obsidian-book-search-plugin#85]
Hi!
I've searched but didn't find any reference but maybe is my fault.
I wish to know if it would be possible to add the book's plot, possibly in the language of the search (Italian, in my case).
Thanks a lot for any help

**Comment by luckylat** [comment]
if you want to set plot in generated page, please add `{{description}}` in template page.
Ref: https://github.com/anpigon/obsidian-book-search-plugin#template-variables-definitions

---
If the above does not resolve the issue, please read below.

Some book haven't description in Google Book API. 
if you want to confirm a book has description, the page is will help.
```
https://www.googleapis.com/books/v1/volumes?q={{books title}}&langRestrict=it
```
ex; `https://www.googleapis.com/books/v1/volumes?q=test&langRestrict=it`

if searched book has the description, it set `description` like this. 
![2023-10-24-085648_1494x606_scrot](https://github.com/anpigon/obsidian-book-search-plugin/assets/40878560/46aec92a-e98d-493f-8310-84caaeccb347)

---

**Comment by ruben-sg** [comment]
Adding to this: Any ideas for getting a complete summary? The description often (quite rightly!) is one without spoilers. But after having read a book, I would love to have a complete summary I can go back to.
