### ISSUE TITLE
[FEATURE REQUEST] Category as List

### ISSUE THREAD

**Issue by Smurfz87** [anpigon/obsidian-book-search-plugin#91]
Many books have a multitude of categories associated with them. 

Support a list of categories as done with the "authors" variable. 

Google Book's API returns a list of categories.

**Comment by Drakemoor** [comment]
I've tried this with templater but it only returns one category. 
```markdown
categories: <%=book.categories.map(category=>`\n  - ${category}`).join('')%>
```

**Comment by anpigon** [comment]
> I've tried this with templater but it only returns one category.
> 
> ```
> categories: <%=book.categories.map(category=>`\n  - ${category}`).join('')%>
> ```

The Google Books API typically provides only one category for the majority of books. Unfortunately, I'm unable to assist with this matter. I am in the process of searching for alternative APIs apart from Google Books Search.

**Comment by Drakemoor** [comment]
This is what I understood also. Thanks for your help and the work you do on the plugin.
