### ISSUE TITLE
Card view not working anymore?

### ISSUE THREAD

**Issue by ruben-sg** [anpigon/obsidian-book-search-plugin#92]
I installed the plugin some weeks ago and all was working perfectly fine. I haven't come around to really populate my book list, but wanted to have a go at it after the holidays. Today, I checked the draft of my overview and the card view does not seem to be working anymore. The problem is with the cssclass "cards" I have set in a property. If I delete that, the dataview tables work fine (but obviously as tables, not as cards). Does it have something to do with Obsidians updates to tables?

EDIT: I just realised that this is not a question for you. The css-Snippet I used stopped working with other themes than Minimal (for which it was created). I'm using Material Gruvbox, if anyone has an idea on how to solve this.

**Comment by hewittaj** [comment]
Not sure if this is the same problem, but I had to go to Settings - Appearance and then check for updates for the community themes. You may also have to use 'cssClasses' as the property name instead of 'cssclass'. 

Hopefully that works!

**Comment by ruben-sg** [comment]
I completely forgot about this thread. I managed to solve the problem a few days ago. But I can't really recall what it was in the end. It might have been an issue with the dataview code that worked before but didn't anymore.
